### ISSUE TITLE
Cypress AuthGuard causing issues

### ISSUE THREAD

**Issue by muhamedkarajic** [rainerhahnekamp/angular-cypress#1]
I have the issue that we have a AuthGuard which we use at a lot of places which ultimatly causes the issue for cypress component tests. So far I haven't found a solution there, what I can say is that I have even tried to just return always true from the AuthGuard but that didn't work.

We are using those 2 libraries for auth
    "@azure/msal-angular": "^3.0.1",
    "@azure/msal-browser": "^3.0.1"

If any information is needed just let me know.

**Comment by muhamedkarajic** [comment]
I think I messed up the place to post the issue. Sorry.

**Comment by rainerhahnekamp** [comment]
No worries, do you include the full Angular router in the component test?
